---

version: "3.2"

networks:
  zenko-net:
    driver: overlay
    attachable: true

services:
  s3:
    image: scality/s3server
    ports:
      - "8000"
    networks:
      - zenko-net 
    volumes:
      - ./config.json:/usr/src/app/config.json

  lb:
    image: zenko/loadbalancer
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: 80
      UPSTREAM_SERVER: s3:8000
    networks:
      - zenko-net
